Grad_Project/Controllers/AttendanceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Grad_Project.Models;
using PagedList;

namespace Grad_Project.Controllers
{
    public class AttendanceController : Controller
    {
        private LMSDBEntities db = new LMSDBEntities();

        // GET: Attendance
        [Authorize(Roles = "Admin, Student, Lecturer")]
        public ActionResult Index(string Search, string Courses, int? Page_No)
        {
            var attendance_tbl = db.Attendance_tbl.AsQueryable();
            if (User.IsInRole("Lecturer"))
            {
                var lec = db.Lecturer_tbl.FirstOrDefault(m => m.Email == User.Identity.Name);
                ViewBag.Courses = new SelectList(db.Course_tbl.Where(m => m.Prof == lec.ID || m.Assistant == lec.ID), "ID", "Name");
                attendance_tbl = db.Attendance_tbl.Include(a => a.Course_tbl).Include(a => a.Student_tbl).Where(m => m.Course_tbl.Prof == lec.ID ||
                m.Course_tbl.Assistant == lec.ID);
            }
            else if (User.IsInRole("Student"))
            {
                var std = db.Student_tbl.FirstOrDefault(m => m.Email == User.Identity.Name);
                var reg = db.RegisteredCourses_tbl.Find(std.ID);
                ViewBag.Courses = new SelectList(db.Course_tbl.Where(m => m.ID.Contains(reg.Course01) || m.ID.Contains(reg.Course02)
                || m.ID.Contains(reg.Course03) || m.ID.Contains(reg.Course04) || m.ID.Contains(reg.Course05)
                || m.ID.Contains(reg.Course05) || m.ID.Contains(reg.Course06)), "ID", "Name");
                attendance_tbl = db.Attendance_tbl.Include(a => a.Course_tbl).Include(a => a.Student_tbl).Where(m => m.StudentID == std.ID);
            }
            else //Admin
            {
                ViewBag.Courses = new SelectList(db.Course_tbl, "ID", "Name");
                attendance_tbl = db.Attendance_tbl.Include(a => a.Course_tbl).Include(a => a.Student_tbl);
            }
            
            int Size_Of_Page = 6;
            int No_Of_Page = (Page_No ?? 1);
            if (!string.IsNullOrEmpty(Courses))
            {
                attendance_tbl = attendance_tbl.Where(m => m.CourseID.Contains(Courses));
            }
            if (!string.IsNullOrEmpty(Search))
            {
                return View(attendance_tbl.Where(m => m.StudentID.Contains(Search)).ToList().ToPagedList(No_Of_Page, Size_Of_Page));
            }

            return View(attendance_tbl.ToList().ToPagedList(No_Of_Page, Size_Of_Page));
        }

        // GET: Attendance/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendance_tbl attendance_tbl = db.Attendance_tbl.Find(id);
            if (attendance_tbl == null)
            {
                return HttpNotFound();
            }
            return View(attendance_tbl);
        }

        // POST: Attendance/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Attendance_tbl attendance_tbl = db.Attendance_tbl.Find(id);
            db.Attendance_tbl.Remove(attendance_tbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Grad_Project/Views/Attendance/Delete.cshtml
@model Grad_Project.Models.Attendance_tbl

<div class="margin_30_95" style="margin-left:30px;">
    <h2>Are you sure you want to delete this?</h2>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("No of Attendances")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.No_of_Attendances)
            </dd>

            <dt>
                @Html.DisplayName("Course")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Course_tbl.Name)
            </dd>

            <dt>
                @Html.DisplayName("Student")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Student_tbl.Name)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> &ensp;
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success"})
            </div>
        }
    </div>
</div>

Grad_Project/Views/Attendance/Index.cshtml
@model PagedList.IPagedList<Grad_Project.Models.Attendance_tbl>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />

<div class="margin_30_95" style="margin-left:30px;">
    <h2>List of Attendance</h2>

    @using (Html.BeginForm("Index", "Attendance", FormMethod.Get, new { @class = "horizontal-form" }))
    {
        <div>
            <div class="form-group">
                @Html.Label("Choose The Course", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Courses", null, "Select Course", htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
        </div>
        <br />
        <br />
        <div class="form-group">
            @Html.Label("Search Box (Use ID Code): ", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Search", null, new { @class = "form-control", @style = "display:inline-block;" })
                <button type="submit" value="Search" style="display:inline-block;" class="btn btn-primary">Search</button>
            </div>
        </div>
    }
    <br />
    <br />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("No of Attendances")
            </th>
            <th>
                @Html.DisplayName("Course")
            </th>
            <th>
                @Html.DisplayName("Student")
            </th>
            @if (User.IsInRole("Admin"))
            {
                <th></th>
            }
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.No_of_Attendances)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course_tbl.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Student_tbl.Name)
                </td>
                @if (User.IsInRole("Admin"))
                {
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                }
            </tr>
        }

    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, Page_No => Url.Action("Index",
    new { Page_No }))
</div>