Grad_Project/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Grad_Project.Models;
using PagedList;

namespace Grad_Project.Controllers
{
    public class ResultController : Controller
    {
        private LMSDBEntities db = new LMSDBEntities();

        // GET: Result
        [Authorize(Roles = "Lecturer, Student")]
        public ActionResult Index(string Search, int? Page_No)
        {
            var result_tbl = db.Result_tbl.Include(r => r.Course_tbl).Include(r => r.Student_tbl);
            if (User.IsInRole("Student"))
            {
                var std = db.Student_tbl.FirstOrDefault(m => m.Email == User.Identity.Name);
                result_tbl = db.Result_tbl.Where(m => m.StudentID == std.ID).Include(r => r.Course_tbl).Include(r => r.Student_tbl);
            }
            
            int Size_Of_Page = 6;
            int No_Of_Page = (Page_No ?? 1);
            if (!string.IsNullOrEmpty(Search))
            {
                return View(result_tbl.Where(m => m.Title.Contains(Search)).ToList().ToPagedList(No_Of_Page, Size_Of_Page));
            }
            return View(result_tbl.ToList().ToPagedList(No_Of_Page, Size_Of_Page));
        }
        
        //AutoComplete mechanism for student code
        public JsonResult SearchStd(string term)
        {
            List<string> Loc = db.Student_tbl.Where(x => x.ID.Contains(term)).Select(x => x.ID).ToList();
            return Json(Loc, JsonRequestBehavior.AllowGet);
        }

        //AutoComplete mechanism for course code
        public JsonResult SearchCourse(string term)
        {
            List<string> Loc = db.Course_tbl.Where(x => x.ID.Contains(term)).Select(x => x.ID).ToList();
            return Json(Loc, JsonRequestBehavior.AllowGet);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Grad_Project/Views/Result/Create.cshtml
@model Grad_Project.Models.Result_tbl

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Result_tbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="StudentBar" class="form-group">
            @Html.LabelFor(model => model.StudentID, "Student", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="CourseBar" class="form-group">
            @Html.LabelFor(model => model.CourseID, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total_Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total_Mark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total_Mark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Achieved_Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Achieved_Mark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Achieved_Mark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts{
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            var std = $('#StudentID');
            var c = $('#CourseID');
            //Autocomplete
            std.autocomplete({
                source: '@Url.Action("SearchStd")'
            });
            c.autocomplete({
                source: '@Url.Action("SearchCourse")'
            });
        });
    </script>    
}

Grad_Project/Views/Result/Delete.cshtml
@model Grad_Project.Models.Result_tbl

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Result_tbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_Mark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_Mark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Achieved_Mark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Achieved_Mark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_tbl.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_tbl.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student_tbl.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student_tbl.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Grad_Project/Views/Result/Details.cshtml
@model Grad_Project.Models.Result_tbl

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Result_tbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Total_Mark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_Mark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Achieved_Mark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Achieved_Mark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_tbl.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_tbl.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student_tbl.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student_tbl.Name)
        </dd>

    </dl>
</div>
@if (User.IsInRole("Lecturer"))
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
}
else
{
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Grad_Project/Views/Result/Edit.cshtml
@model Grad_Project.Models.Result_tbl

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Result_tbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="CourseBar" class="form-group">
            @Html.LabelFor(model => model.CourseID, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="StudentBar" class="form-group">
            @Html.LabelFor(model => model.StudentID, "Student", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total_Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total_Mark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total_Mark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Achieved_Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Achieved_Mark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Achieved_Mark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts{
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            var std = $('#StudentID');
            var c = $('#CourseID');
            //Autocomplete
            std.autocomplete({
                source: '@Url.Action("SearchStd")'
            });
            c.autocomplete({
                source: '@Url.Action("SearchCourse")'
            });
        });
    </script>
}

Grad_Project/Views/Result/Index.cshtml
@model PagedList.IPagedList<Grad_Project.Models.Result_tbl>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />

<div class="margin_30_95" style="margin-left:30px;">

    <h2>Results List</h2>
    <br />
    @if (User.IsInRole("Lecturer"))
    {
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
    }

    @using (Html.BeginForm("Index", "Result", FormMethod.Get, new { @class = "horizontal-form" }))
    {
        <div>
            @Html.Label("Search Box (Using Title): ", new { @class = "control-label", @style = "display:inline-block;" }) &ensp;
            @Html.TextBox("Search", null, new { @class = "form-control", @style = "display:inline-block;" }) &ensp;
            <button type="submit" value="Search" style="display:inline-block;" class="btn btn-primary">Search</button> <br />
        </div>
        
    }
    <br />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Title")
            </th>
            <th>
                @Html.DisplayName("Course Name")
            </th>
            <th>
                @Html.DisplayName("Student Name")
            </th>
            <th>
                @Html.DisplayName("Total Mark")
            </th>
            <th>
                @Html.DisplayName("Achieved Mark")
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course_tbl.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Student_tbl.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total_Mark)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Achieved_Mark)
                </td>

            </tr>
        }
    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, Page_No => Url.Action("Index",
    new { Page_No }))
</div>