Grad_Project/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Grad_Project.Models;
using PagedList;

namespace Grad_Project.Controllers
{
    public class FileController : Controller
    {
        private LMSDBEntities db = new LMSDBEntities();

        // GET: File
        [Authorize(Roles = "Lecturer, Admin, Student")]
        public ActionResult Index(string Search, string Courses, string assigID, int? Page_No)
        {
            if (User.IsInRole("Student"))
            {
                var stu = db.Student_tbl.Where(m => m.Email == User.Identity.Name).FirstOrDefault();
                var reg = db.RegisteredCourses_tbl.Find(stu.ID);
                if(reg == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                //add registered courses in list
                var stuCourses = new List<Course_tbl>();
                if(reg.Course01 != null)
                {
                    stuCourses.Add(db.Course_tbl.Find(reg.Course01));
                }
                if (reg.Course02 != null)
                {
                    stuCourses.Add(db.Course_tbl.Find(reg.Course02));
                }
                if (reg.Course03 != null)
                {
                    stuCourses.Add(db.Course_tbl.Find(reg.Course03));
                }
                if (reg.Course04 != null)
                {
                    stuCourses.Add(db.Course_tbl.Find(reg.Course04));
                }
                if (reg.Course05 != null)
                {
                    stuCourses.Add(db.Course_tbl.Find(reg.Course05));
                }
                if (reg.Course06 != null)
                {
                    stuCourses.Add(db.Course_tbl.Find(reg.Course06));
                }
                if (reg.Course07 != null)
                {
                    stuCourses.Add(db.Course_tbl.Find(reg.Course07));
                }
                ViewBag.Courses = new SelectList(stuCourses, "ID", "Name");
            }
            else
            {
                ViewBag.Courses = new SelectList(db.Course_tbl, "ID", "Name");
            }
            
            int Size_Of_Page = 6;
            int No_Of_Page = (Page_No ?? 1);

            //Drop down List
            if (!string.IsNullOrEmpty(Courses))
            {
                var course = db.Course_tbl.Find(Courses);
                var fls = new List<File_tbl>();
                fls = db.File_tbl.Where(m => m.CourseID == Courses).ToList();

                //Assig Documents
                if(assigID != null)
                {
                    fls = fls.Where(m => m.AssignmentID == assigID).ToList();
                }
                //Search box
                if (!string.IsNullOrEmpty(Search))
                {
                    return View(fls.Where(m => m.FileName.Contains(Search)).ToPagedList(No_Of_Page, Size_Of_Page));
                    //return View(db.File_tbl.Where(m => m.FileName.Contains(Search)).ToPagedList(No_Of_Page, Size_Of_Page));
                }
                else
                {
                    return View(fls.ToPagedList(No_Of_Page, Size_Of_Page));
                }
            }
            
            return View(db.File_tbl.ToList().ToPagedList(No_Of_Page, Size_Of_Page));
        }
        
        // GET: File/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File_tbl file_tbl = db.File_tbl.Find(id);
            if (file_tbl == null)
            {
                return HttpNotFound();
            }
            return View(file_tbl);
        }

        // POST: File/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            File_tbl file_tbl = db.File_tbl.Find(id);
            db.File_tbl.Remove(file_tbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Grad_Project/Views/File/Delete.cshtml
@model Grad_Project.Models.File_tbl

<div class="margin_30_95" style="margin-left:30px;">
    <h2>Are you sure you want to delete this?</h2>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("File Name")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FileName)
            </dd>

            <dt>
                @Html.DisplayName("Upload On")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UploadOn)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> &ensp;
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success"})
            </div>
        }
    </div>
</div>

Grad_Project/Views/File/Index.cshtml
@model PagedList.IPagedList<Grad_Project.Models.File_tbl>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />


<div class="margin_30_95" style="margin-left:30px;">
    <h2>Documents List</h2>
    @using (Html.BeginForm("Index", "File", FormMethod.Get, new { @class = "horizontal-form" }))
    {
        <div>
            <div class="form-group">
                @Html.Label("Choose The Course", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Courses", null, "Select Course", new { @class = "form-control-sees" })
                </div>
            </div>
            <br />
            <br />
            <div class="form-group" id="SearchBox">
                @Html.Label("File Name:", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("Search", null, new { @class = "form-control-sees" }) &ensp;
                </div>
            </div>
            <input type="submit" value="Search" class="btn btn-sees">
        </div>
        <br />
        <br />
    }
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("File Name")
            </th>
            <th>
                @Html.DisplayName("Upload On")
            </th>
            @if (User.IsInRole("Admin") || User.IsInRole("Lecturer"))
            {
                <th></th>
            }
        </tr>

        @foreach (var item in Model)
        {
            <tr id="tableTR">
                <td>
                    @Html.ActionLink(item.FileName, "ViewFile", "Course", new { Name = item.FileName }, new { @class = "form-label", @id = "File_Hyper", @target = "_blank" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UploadOn)
                </td>
                @if (User.IsInRole("Admin") || User.IsInRole("Lecturer"))
                {
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger"})
                    </td>
                }
            </tr>
        }
    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, Page_No => Url.Action("Index", new { Page_No, Search = Request.QueryString["Search"], Courses = Request.QueryString["Courses"] }))
</div>